### ISSUE TITLE
Loading Normal Mode Wizard in Chimera 1.15

### ISSUE THREAD

**Issue by shonkoren** [prody/ProDy#1319]
I've been trying to load the Normal Mode Wizard in Chimera (v1.15, Win10 OS), but can't get the plugin to load in. I've successfully loaded in another chimera plugin so I know my general Plugin folder toolbar location setup is working. I've tried re-downloading the plugin, matching the ChimeraExtension.py with the plugin that worked adjusting for NMWs-specific details, changing the toolbar location of the plugin from 'Structure Editing' to another one, but all of these have failed.

Love the program and the wizard in VMD, but Chimera is my tool for choice for pretty pictures so I'd really appreciate any help in getting it loaded in Chimera. Thanks for your time.

**Comment by jamesmkrieger** [comment]
Thanks for reporting this. I had also been having problems but didn’t know if they are general. I’ll see what I can do to sort it out

**Comment by jamesmkrieger** [comment]
I have managed to get the Normal Mode Wizard to open in Chimera v1.15 on Win 10. The solution was as follows:

1. make a new conda environment with Python 2.7, numpy, scipy and biopython 1.76 
2. set my PYTHONPATH and PythonPath to include C:/Users/james/.conda/envs/python2/lib/site-packages so that the Chimera python can see it
3. put /c/Program Files/Chimera 1.15 precomp/bin and /c/Program Files/Chimera 1.15 precomp/bin/Scripts and my PATH
4. copy the NMWiz-chimera directory from github to /c/Program Files/Chimera 1.15 precomp/share and rename it as NMWiz

Some functionalities don't work but some do. For example, I can load in an NMD file and make a movie with the default of 2.0 A displacement but can't change it. If I change the number and press draw then the arrows aren't drawn and the number isn't really updated. If I use the buttons to increase and decrease by 0.5 or 0.1 then the arrows get updated but the movie breaks. I likewise can't change to the next mode. 

Still is a good starting point and I can try to fix these various things.

**Comment by jamesmkrieger** [comment]
If I increase the number with the buttons without pressing draw then it works and I can make movies with increased size incidentally.

**Comment by jamesmkrieger** [comment]
Seeing as NMWiz for Chimera was never properly completed and has so many problems, we can't really support it, but feel free to do so yourself. 

For now, this issue is closed though. Thanks again for your interest in it and sorry we can't be more helpful.

**Comment by shonkoren** [comment]
Thank you for looking into the solution so quickly! Will try later today, I don't need any functionality other than default movies, so this is great. Thanks again

**Comment by jamesmkrieger** [comment]
You're welcome. Hopefully you'll still say that when you've tried it. You really can only show the first mode in the NMD file, but I guess a workaround is to write NMD files for each mode separately.
