### ISSUE TITLE
unable to replicate PRS results

### ISSUE THREAD

**Issue by ga01** [prody/ProDy#1349]
Dear ProDy Team,
I am trying to use the PRS method in my work, and it seems that I am unable to replicate the results shown on the ProDy homepage (Dutta et al. 2015, Structure, using PDB 3kg2). I use Prody 2.0, BioPython 1.74, numpy 1.16.0, scipy 1.2.3.  

Basically, the effectiveness and sensitivity profiles do not match the ones shown on the homepage, and they are also not different from each other. I wonder whether I am missing something fundamental, I have an installation problem, or a bug (I get no error messages while running the PRS commands). I would be grateful for any help with this issue.  

Kind Regards, 
George

PS.: I use the following code:

from prody import *
from pylab import *

ion()
ampar_ca = parsePDB('3kg2', subset='ca')
anm_ampar = ANM('AMPAR 3kg2')
anm_ampar.buildHessian(ampar_ca)
anm_ampar.calcModes()

#saveModel(anm_ampar, '3kg2', matrices=True)
#anm_ampar = loadModel('3kg2.anm.npz')
#ampar_ca = parsePDB('3kg2', subset='ca')

prs_mat, effectiveness, sensitivity = calcPerturbResponse(anm_ampar)

B_475_effectiveness = sliceAtomicData(prs_mat, atoms=ampar_ca, axis=0, select='chain B and resnum 475')
B_475_sensitivity = sliceAtomicData(prs_mat, atoms=ampar_ca, axis=1, select='chain B and resnum 475')

writePDB('3kg2_ca_B_475_effectiveness.pdb', ampar_ca, betas=B_475_effectiveness)
writePDB('3kg2_ca_B_475_sensitivity.pdb',   ampar_ca, betas=B_475_sensitivity)

**Comment by ga01** [comment]
PS.: It seems that the  B_475_effectiveness and B_475_sensitivity arrays differ, so the problem might be with the writePDB function

**Comment by jamesmkrieger** [comment]
I think the problem may be that you are only using the default of 20 modes with anm_ampar.calcModes() and one should really use all of them for PRS. Please try that and let us know if that works. 

Another thing to bear in mind when writing to PDB is that the scale of the numbers may not fit the b-factor field very well so you may need to multiply or divide by a few powers of ten to shift the decimal places appropriately.

Best wishes 
James

**Comment by jamesmkrieger** [comment]
Also, the effectiveness and sensitivity profiles are supposed to differ from each other so that’s not a problem. That’s the whole point of the ProDy implementation of PRS

**Comment by jamesmkrieger** [comment]
Please do let me know whether all modes works and if it does I’ll update the tutorial page. Thanks

**Comment by ga01** [comment]
Hi James, 
Thank you. I re-run the script, with anm_ampar.calcModes(n_modes='all'), i got no error messages.  The problem remains though, B_475_effectiveness and B_475_sensitivity arrays differ (they should), but the 3kg2_ca_B_475_effectiveness.pdb and 3kg2_ca_B_475_sensitivity.pdb files do not, and their B-factors also differ from the expected (should be as in B_475_sensitivity and B_475_effectiveness arrays). So it seems that there is a problem with the writePDB function, it does not modify b-factors correctly, and it simply uses the original B-factors from 3kg2. 

Kind Regards, 
George

PS.: I wonder whether it would make sense to restrict the number of modes? For this structure (3kg2) there are ~9000 modes, and with Bio3D, the authors reported that generally using only the first 400 modes is the most accurate in replicating fluctuations and correlations obtained with MD. Are there any benchmarks on this for PRS?

**Comment by jamesmkrieger** [comment]
As I said above, you need to scale the B_475_effectiveness and B_475_sensitivity arrays when writing to PDB. I don't remember what the scaling factor is but I can have a look.

As for number of modes, in theory the higher the number the better PRS should be as the local motions are likely important for signal propagation but at the same time the higher modes will contribute less and less so you are right there will be a balance point that will save on computation time while still being accurate. I don't think there has been any benchmark on this though.

As for the comment that the Bio3D authors reported that the first 400 modes is the most accurate in replicating fluctuations and correlations from MD, I'm not sure how much we can trust that as I haven't read it recently but my intuition is that this really depends on protein size and isn't a hard and fast rule. I'd be very surprised if they studied such large proteins systematically but I'll have a look. There's also the issue of how long the MD simulations are too as that could also make a difference, I remember a paper by the Atilgans where they compared normal modes PRS to MD simulations and said that 40 ns was the best but I don't recall how many modes they used or whether they optimised that. 

I think all we can say at this point is that 20 modes isn't enough to give a good agreement with the result from all modes.

**Comment by ga01** [comment]
Hi James, 
I converted all sensitivity values to a dd.dd format (range 0.01 - 99.99), so it definitely fits the valid range and format of temperature factors in PDB files, but writePDB still doesn't use them. So it seems that the "betas" options doesn't work correctly, certainly not the way it is used in the PRS tutorial. (Whatever I do it uses the original b-factors of the PDB file.)  

Another thing - can one perform PRS with ligands included, or using all atoms? With C-alphas only computing time is relatively low (minutes), so it may not be prohibitive for all atoms, but I'm not sure whether the implemented algorithm permits it, or whether the results would be meaningful.

Best wishes, 
George

**Comment by jamesmkrieger** [comment]
Hi George,

I think your problem with writePDB is you need to use beta not betas. I guess I need to change the PRS tutorial to account for that.

Yes, it should be possible to use all atoms including ligands in elastic network model normal mode analysis and PRS though this hasn’t been tested as far as I know. The original ENM of Monique Tirion used all atoms but I don’t recall what the cutoff was. 

Alternatively, there’s the approach used in Markov signal propagation of using the numbers of heavy atoms for the construction of the connectivity (adjacency) matrix and then performing the calculations on residues after that. Again I don’t know how you’d set that up but it is definitely an option I’ve been thinking about. The Markov signal propagation analysis (calcHitTime) could also be a good alternative to PRS.

There’s also the mixed resolution model RESPEC although that still needs to be incorporated into ProDy I think.

Another alternative to PRS that can account for atoms including ligands I think is essential site scanning analysis (ESSA).

Best wishes
James

**Comment by jamesmkrieger** [comment]
I’ve no idea whether the results would be meaningful using the all atom ENM either but it doesn’t hurt to try

**Comment by ga01** [comment]
Hi James, 
Success - I could reproduce the results of the Dutta et al. 2015 paper. Thanks for your help. I'm trying several methods right now, and PRS seems to be the thing I'm looking for, although having ligands in the structure would be better. I will definitely try the all-atomic version.

Best wishes, 
George

**Comment by jamesmkrieger** [comment]
You’re very welcome. Glad it worked.

The fixes were 1) use all modes and 2) writePDB with beta not betas, right?

**Comment by jamesmkrieger** [comment]
I’d also be very interested in hearing what happens with the all atom approaches. Feel free to email me about them at jamesmkrieger@gmail.com

**Comment by ga01** [comment]
Thank you, yes, in retrospect it was trivial. I did a quick test for all atoms, using the same code, except the atom selection ( parsePDB('2spl', subset=None) ) using a random myoglobin structure 2spl. It works, but the function 
sliceAtomicData(prs_mat, atoms=ampar_ca, axis=1, select='chain A and resnum 49') 
returns eight values for every atom, so I'm not sure how to handle that, i.e. how to calculate sensitivities for atoms (or even better, residues):

[[3.45349333e-03 3.74130181e-03 4.11707696e-03 3.63293379e-03 2.89701540e-03 2.82766635e-03 2.12308817e-03 3.84898212e-03]
 [4.27226323e-03 4.54041994e-03 4.95129633e-03 4.38249243e-03 3.50104769e-03 3.42246046e-03 2.55442467e-03 4.58573484e-03]
...

Maybe the ANM or CalcPerturbResponse have to be modified.

Best wishes, 
George

**Comment by jamesmkrieger** [comment]
I’d suggest averaging over the atoms in a residue perhaps. I think the PRS functions can all handle selections of multiple atoms as this done for calpha atoms of multiple residues sometimes but please let me know if it doesn’t

**Comment by ga01** [comment]
Thanks; my impression is that using all atoms in PRS would need a substantial amount of benchmarking. I wonder whether residue center of mass (c.o.m.) has ever been tested with PRS. It is a simple alternative to C-alphas, and generally it performs better than C-alphas, at least in community analyses. I know it is not currently implemented in ProDy, but maybe it would be worth it (but it is easy to modify the structures prior the analysis to use c.o.m.)
Best wishes, 
George

**Comment by jamesmkrieger** [comment]
Hi George,

I am not aware of anyone testing any variants of PRS at all. As far as I know, it has always been performed using Calpha atoms with the covariance matrix coming from either GNM, ANM, or PCA of MD simulations. I agree it would need benchmarking to work out how to incorporate other kinds of information and probably new theoretical studies too. 

There is also a method based on perturbing springs rather than nodes from Zheng, Brooks and Thirumalai that also works called the Structural Perturbation Method (SPM), which came before PRS and also worked so clearly other approaches are valid. 

The original application of linear response theory to proteins (https://pubmed.ncbi.nlm.nih.gov/15783858/), on which PRS is based, also used all-atom covariance matrices I think so it should be doable. In that case they used MD simulations to generate the covariance matrix and that seems like the best idea to me too. You can slice the MD coordinates in ProDy to only use the motions of the Calpha atoms for generating the covariance matrix (via PCA) and PRS as a per-residue read-out if you like or calculate the c.o.m. motion of residues if you prefer. In both cases, this would show the influence on the residue of all-atom interactions including those with the ligand.

As for using centers of mass of residues directly in ENMs for PRS, I don't see any reason not to use them. I believe they have been used in elastic network model normal mode analysis with no issues and doing the same for PRS sounds ok to me. The global modes that have the highest contribution to the covariance are robust against model details so the question is really how many modes are important to PRS and hence how much the high frequency details matter. Again, I'd suggest you to look at the literature and see how other people have done it. You may still get push back from reviewers if you don't justify and benchmark the approach though. 

As for the implementation, it is fairly easy to extract the residue c.o.m. coordinates as you said so there is no reason to modify ProDy. You can simply provide those coordinates to the ANM or GNM calculation instead of a selection of atoms.

Two other things you could try are the following:

1. Using all-atom force fields from MD for NMA, which the classical way that NMA was done before ENMs were introduced. ProDy cannot perform these calculations but it isn't too difficult to parse the outputs from other programs. I think I have a script somewhere for doing this with the output from CHARMM. You could then slice out the Calpha components of the modes and use them to calculate the covariance matrix, which would then have the motions of the Calpha atoms under the influence of interactions between all atoms or calculate c.o.m. coordinates to use instead. You could in theory do the same thing for the all-atom ENM as well, but again it could be more questionable although maybe not.

2. Using the regular Calpha ENMs but adding one or mode nodes for each ligand. Which position(s) you choose is up to you. It could be some representative atom(s) or the c.o.m. of the whole ligand or some parts of it. It is again questionable what is a reasonable way to do this and it really depends on the ligand size and shape.

Best wishes
James

**Comment by jamesmkrieger** [comment]
Now that the website tutorial is fixed and we have progressed to more detailed discussions that can better be had via email, this issue is closed. 

Thanks again, George, for reporting these problems and starting these interesting discussions.
