### ISSUE TITLE
Summary structures of clusters (similar conformations) from ensemble analysis

### ISSUE THREAD

**Issue by b2jia** [prody/ProDy#1424]
I'm following the richly documented tutorial on [ensemble analysis](http://prody.csb.pitt.edu/tutorials/ensemble_analysis/xray_calculations.html), which dives into the p38 MAPK structural dataset. Since the structures are heterogeneous in both structure and sparsity, my interpretation is the ensemble analysis enables some degree of imputation? Where one structure might be missing values, it can be 'imputed' from a similar structure?

This leads to my question - what does it take to reproduce the Fig 1B in Bakan et al. PNAS 2009 (https://www.pnas.org/content/pnas/106/34/14349.full.pdf)? Presumably, the green fiber is a "summary structure" of all of the different configurations belonging to group `1N6Q`. Similarly, the red fiber is a "summary structure" of all of the different configurations belonging to group `1HQE`. Is there a specific terminology for what I'm describing? Is it as simple as finding the median `[x, y, z]` of all of the structures belonging to a group? I find this type of analysis incredibly interesting!

![image](https://user-images.githubusercontent.com/37123556/140686608-0aa9faa1-109a-41fb-8e90-f8159b00b210.png)

**Comment by jamesmkrieger** [comment]
Yes, in theory one could impute missing parts of the structure from similar structures. The ensemble analysis actually does something similar for the whole set of structures: if a structure lacks atoms, dummy atoms are placed at the mean position of that atom across all the structures. If you wanted to use similar structures you’d just need to build a new ensemble using only those structures.

Probably the best way to go would be to build a distance tree in PC space or using RMSDs, then use the findSubgroups command and select the ones with the representative members of your choice. You can also reorder the distance matrix by the tree with reorderMatrix and get reordering indices too for reordering the ensemble and labels. This can help with seeing the clustering patterns too. We also have other clustering tools in ProDy, which you can try. 

Based on that you can then project different subsets of the ensemble onto the PC reduced space in different colours as a sanity check and try to match that Figure. I’d imagine it was done manually and reflects some functional properties such as ligand type or activation state.

**Comment by b2jia** [comment]
I see, thank you for this clarification! Just making sure here:

> The ensemble analysis actually does something similar for the whole set of structures: if a structure lacks atoms, dummy atoms are placed at the mean position of that atom across all the structures.

When the ensemble is built ie. `ensemble = buildPDBEnsemble(structures, title='p38 X-ray')` , does `ensemble.iterpose()` perform some type of Procrustes analysis to align all of the heterogenous structures? Does it align by the first residue?

**Comment by jamesmkrieger** [comment]
> I see! Thank you so much for this clarification! Just making sure here:
> 
> > The ensemble analysis actually does something similar for the whole set of structures: if a structure lacks atoms, dummy atoms are placed at the mean position of that atom across all the structures.
> 
> When the ensemble is built ie. `ensemble = buildPDBEnsemble(structures, title='p38 X-ray')` , does `ensemble.iterpose()` perform some type of Procrustes analysis to align all of the heterogenous structures? Does it align by the first residue?

Nothing as sophisticated as a Procrustes analysis, no. There are many methods that can be used to match the residues in `buildPDBEnsemble` and by default it starts by trying to match the residue numbers, then tries biopython sequence alignment, then tries cealign. It's all based on the reference structure. When you then run `ensemble.iterpose()` it keeps those matchings and performs a superposition to the reference structure and updates it with the mean structure and repeats that through a few iterations until the mean structure converges to some limit.

As you say the structures are heterogeneous so it can introduce gaps in the matching for missing parts and it has to fill these gaps with something so these are dummy atoms and their position is from the reference coordinates. Usually this is the average structure because `ensemble.iterpose()` is run by default, but you can turn off this behaviour. You can also set a particular coordinate set from the ensemble so actually that could do what you want of taking it from a similar structure.

> 
> > Probably the best way to go would be to build a distance tree in PC space or using RMSDs, then use the findSubgroups command and select the ones with the representative members of your choice.
> 
> Say I were to subset the structures from `1N6Q`, and build an ensemble from them. Is the summary structure extracted by `ensemble.getCoords()`? 

Yes, what you get with `ensemble.getCoords()` is the reference coordinates, so if you were to build an ensemble from the subset around 1N6Q then you'd get the mean structure of the subset ensemble if `ensemble.iterpose()` had been used, which would be your summary structure, yes.

> I read somewhere in the documentation if there is no default structure then by default the coordinates of the first member of the subgroup is returned.

No, this isn't for `getCoords()` but for `buildPDBEnsemble`. If you create an `Ensemble` or `PDBEnsemble` object some other way such as with `parseDCD` then it returns `None` not the coordinates of the first member of the ensemble.

**Comment by b2jia** [comment]
Thank you for your detailed response!

**Comment by jamesmkrieger** [comment]
You’re very welcome
