### ISSUE TITLE
PCA Analysis 

### ISSUE THREAD

**Issue by ezgisoydemir** [prody/ProDy#1557]
Hello, Im trying to do PCA Analysis with ProDy. I downloaded the ProDy in its website and clone the scripts from here to my Prody folder in the python's site packages folder. Then I added prody in my path. (I did these steps since I got another error too) But in the beginning step of the PCA analysis, I can't add atoms while using "prody fetch" command in the TK console. I'm not sure what did I wrong cause all these stuffs are new for me. I would be glad if you help, thank you.

C:\Users\usr\Downloads>C:\Users\usr\AppData\Local\Programs\Python\Python310\lib\site-packages\ProDy-2.1.2.dist-info\ProDy\scripts\\..\python C:\Users\usr\AppData\Local\Programs\Python\Python310\lib\site-packages\ProDy-2.1.2.dist-info\ProDy\scripts\\prody fetch ionized_clear.pdb 
'C:\Users\usr\AppData\Local\Programs\Python\Python310\lib\site-packages\ProDy-2.1.2.dist-info\ProDy\scripts\\..\python' is not recognized as an internal or external command,
operable program or batch file.

**Comment by jamesmkrieger** [comment]
The problem is probably that you’re using the tk console. You should be running these commands on a regular terminal. 

You probably also don’t need to provide these full paths if you have Python and ProDy in your path, but I don’t know what exactly you’ve done so maybe you do.

You should also be able to just use prody fetch without python before it as prody is set up to have apps like that.

Let me know whether that works for you or if you have any more questions.

Best wishes 
James

**Comment by jamesmkrieger** [comment]
Did you actually install prody? Cloning it isn’t enough. You should really build the c extensions too. 

It may be that putting it in site packages is enough for python to know it’s there but I’m not convinced about that. You may also need to put the internal prody directory there and not the whole ProDy directory that comes from cloning. 

I’d be interested to see what happens though.

Does it work to open python and type import prody?
