### ISSUE TITLE
DNA junction MD trajectory_PCA analysi

### ISSUE THREAD

**Issue by ShivBharadwaj** [prody/ProDy#1581]
Hello! 

I am wondering if I can this tool for PCA analysis and other properties for the DNA junction MD simulation trajectory.

Thank you in advance and would you share the info on the same if possible? 

Best 
Shiv

**Comment by jamesmkrieger** [comment]
Hello,

Yes, these methods should be applicable to any system including your one with DNA. You would just follow the PCA tutorials that we have and change the selections to something relevant for DNA such as the phosphorus atoms.

let us know if you have any more specific questions.

best wishes 
James

**Comment by jamesmkrieger** [comment]
Yes, it’s ok to focus on a particular region such as a chain for PCA and identify the movements within that rather than just selecting all the phosphorous atoms.

One thing that could be nice too is to use sliceModel on the full PCA and compare the resulting modes of variation to those from the focused analysis and see what movements of the whole system are coupled to the PC movements of the focused analysis.

PCA is actually very amenable to such analyses as you’re taking data from your simulation and just doing a post analysis so there’s no change in the physics
