### ISSUE TITLE
Biopython pairwise2.py:278

### ISSUE THREAD

**Issue by girodat** [prody/ProDy#1720]
Hi, I'm trying to perform a principal component analysis on a simulation using prody through VMD. 

When I try to perform the PCA I am receiving the error:

/Users/dgirodat/opt/anaconda3/lib/python3.9/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
/Users/dgirodat/opt/anaconda3/lib/python3.9/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
    while executing
"exec $::NMWiz::pybin $::NMWiz::prody {*}$args"
    (procedure "::NMWiz::prodySubmitPCAjob" line 61)
    invoked from within
"::NMWiz::prodySubmitPCAjob"
    (procedure "::NMWiz::prodySubmitJob" line 26)
    invoked from within
"::NMWiz::prodySubmitJob"
    invoked from within
".nmwizprody.submitFrame.prodySubmit invoke"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke]"
    (procedure "tk::ButtonUp" line 23)
    invoked from within
"tk::ButtonUp .nmwizprody.submitFrame.prodySubmit"
    (command bound to event)

Any ideas what is happening with this depreciation warning?

Thank you,
Dylan

**Comment by jamesmkrieger** [comment]
Hi Dylan,

The problem here is that getting any warning breaks the NMWiz ProDy interface.

Biopython are telling people that they are changing how they handle pairwise alignments in future versions, so that we can change our code in time. In fact, I have already done so in #1636, which is already included in ProDy 2.4.0

Are you using an older version of ProDy and can you update yours? 

I'd suggest using the latest development version from Github as 2.4.0 has some problems and we haven't got round to making another release yet. You can do that following http://prody.csb.pitt.edu/manual/devel/develop.html

Best wishes
James

**Comment by girodat** [comment]
Dear James,

Thanks, I had recently installed ProDy so I didn't think that a newer
version would be available. After installing 2.4 it is working now.

Thank you,
Dylan

**Comment by jamesmkrieger** [comment]
You're welcome. I'm glad to hear it's working now. 

It's always worth checking and ProDy is in constant development
