### ISSUE TITLE
Contacts of a trajectory ensemble

### ISSUE THREAD

**Issue by Yago52** [prody/ProDy#1801]
Hello there,

Can you guys help me to get the contacts of a trajectory ensemble?
The ensemble consist of a trajectory of molecular dynamics with a protein + ligand complex. 
chain that represents the protein: chain X
chain that represents the ligand: chain Y

This is what I have tried:
```python

ref = parsePDB('TTT_chain_correct.pdb')

ensemble = parseDCD('TTT_v1_fix.dcd')
ensemble.setCoords(ref)
ensemble.setAtoms(ref)
```
From here I have tried to create multiple pdbs to calculate the contacts of each PDB, but the problem is that when I do that the chains get renamed and the problem continues.

I have tried to make a selection of each chain in the ensemble to calculate the contacts directly, but without sucess.

**Comment by jamesmkrieger** [comment]
@karolamik13 lab are developing a new interactions module called InSty specifically for this and you should be able to find it in the GitHub version of prody. There are also tutorials on the GitHub version of the prody website: https://github.com/prody/ProDy-website/tree/master/tutorials/insty_tutorial

The idea is to be able to analyse protein-protein, protein-water and protein-ligand interactions directly from trajectories as well as ensembles and single structures. Please try it and let us know if you have any problems.

**Comment by karolamik13** [comment]
Hello,
If you want to check interactions within protein between two proteins, you can use (4_TUTORIAL4_paper.ipynb) for trajectory analysis, which is available in the folder **ipynb_files** ( https://github.com/prody/ProDy-website/tree/master/tutorials/insty_tutorial). Everything is explained step by step.

As for protein-ligand interaction module (which is under development) the tutorial is not ready yet, but functions should be available in the version which is on Github. 

Example of usage:
from prody import *

pdb = parsePDB('tric.pdb')
dcd = Trajectory('tric.dcd')

prot_lig_interactions = LigandInteractionsTrajectory()
prot_lig_interactions.calcLigandInteractionsTrajectory(pdb, dcd, start_frame=1, stop_frame=5,filename='LPinter')
# filename - save results in the directory using that option

It will compute interactions for all ligands. This function uses PLIP to detect interactions. Ions is better to remove because PLIP might have a problem with them (NaCl etc)
After that, you can choose which interactions you would like to analyze:
prot_lig_interactions.getLigandsNames()

prot_lig_interactions.getLigandInteractions()
or 
prot_lig_interactions.getLigandInteractions(filters='SBs') # choosing interaction types
prot_lig_interactions.getLigandInteractions(filters='ADP1')  #choosing ligand name

prot_lig_interactions.getLigandInteractionsNumber()
prot_lig_interactions.calcFrequentInteractors(selection=None)
prot_lig_interactions.calcFrequentInteractors(selection='ADP1A')

I will prepare a jupyter notebook with examples when I find more time.

Let me know if you will need help.
Best, Karolina

**Comment by Yago52** [comment]
Thanks for the help, with the tutorial I have done it.

**Comment by jamesmkrieger** [comment]
Great! Do you have any comments for us on anything that could be better seeing as you're one of the first users of this new functionality?
