### ISSUE TITLE
Average spring constant kappa calculation 

### ISSUE THREAD

**Issue by Vini161** [prody/ProDy#1916]
I could use a clarification if we can time average kappa based on a sample of a few frames from an energy minimized/converged trajectory opposed to a single pdb? Say by running a loop through the sampled frames.Would it violate any of the assumptions on the "equilibrium state" of protein structure

**Comment by jamesmkrieger** [comment]
I guess that sounds reasonable.

If some contacts break and form then you’ll have an average of 0s and 1s and that will make for a weaker spring that can have a wider range of distances more easily

**Comment by Vini161** [comment]
Thank you for the clarification!

**Comment by jamesmkrieger** [comment]
I suppose as long as the trajectory doesn't undergo any large conformational changes, but just fluctuations, then it should be fine.

Another approach you could try is ensemble normal mode analysis in the signature dynamics module. That way, you can calculate the Hessian matrix and normal modes for each frame and then perform averaging on those

**Comment by Vini161** [comment]
Thanks for getting back to me. We checked, and they do not undergo any confirmational changes. We are looking into ensemble analysis. Meanwhile, is it possible to clarify if averaged pdb to represent the backbone aligned trajectory for time intreval in interest would work fine with the framework?

**Comment by jamesmkrieger** [comment]
In theory, I'd say yes, that the equilibrium distances probably should be the average ones across the trajectory. Ultimately, it's up to you to look at the resulting structure and see if it looks reasonable to you. 

This average structure is also what we use in ensemble analysis under the hood and would be the output of ensemble getCoords after iterpose. For PCA, we are looking at variations around the average.

For NMA, probably the frame nearest the average structure (e.g. the one with the minimum RMSD) is a better choice so that you have a physically meaningful reference structure to apply the normal modes to. 

If you're structure isn't really changing much then there probably isn't much difference anyway.

**Comment by Vini161** [comment]
Thank you very much for such detailed explanation. I will look into each one of these

**Comment by jamesmkrieger** [comment]
You're welcome
