### ISSUE TITLE
Code Error in Documentation: Evol Tutorial

### ISSUE THREAD

**Issue by melrom** [prody/ProDy#200]
http://prody.csb.pitt.edu/tutorials/evol_tutorial/comparison.html#writing-pdb-files

The following code does not create a proper entropy_prot array. 

```python
In [28]: for ind in index:
   ....:     while(count < len(resindex)):
   ....:         if(ind == resindex[count]):
   ....:             entropy_prot.append(entropy[ind])
   ....:             mobility_prot.append(mobility_all[ind]*100)
   ....:         count = count + 1
```

You are not resetting the while loop counter when you increment the for loop. Thus, for ind 0, you calculate count<len(resindex), but for ind 1, count is already = len(resindex), and you never enter the while loop. The fix is to reset the counter outside of the while loop but within the for loop.

```python
for ind in index:
    while(count < len(resindex)):
        if(ind==resindex[count]):
            entropy_prot.append(entropy[ind])
            mobility_prot.append(mobility_all[ind]*100)  
        count=count+1
    count=0
```

**Comment by cihankayacihan** [comment]
This issue arised because for this case, the length of sequence is changing since the number of homologous sequences are increased on a daily basis. A right way to solve this problem is to use function mapToChain or use sequence alingment to map the structure on the sequences. We will build our mapper in future.
