### ISSUE TITLE
RMSDs seem very high...

### ISSUE THREAD

**Issue by jwillis0720** [prody/ProDy#213]
ProDy seems like an awesome tool that I'm on the verge of using all the time. However, I'm wondering why all the RMSDs seem so high. Isn't their automatic atom rejection like in pymol? Even when you dump the PDBs, they are very well aligned, but the RMSDs seem inflated. Is there some flag I'm missing? 

Here is few examples with a ipython notebook.
http://nbviewer.ipython.org/gist/anonymous/82de40841a49ade4621b

Also, is this the right place to ask for general help?

**Comment by cihankayacihan** [comment]
Yes. This is right place to ask questions. Your issue is superposition of structures. We have a function called superpose but still it is making a structural alignment based on sequence identity. We are planning to implement a new algorithm for structural alignments. Currently, it is a greedy algorithm for fast structural alignment.
