### ISSUE TITLE
Struggling with how to determine neighboring residues

### ISSUE THREAD

**Issue by bdelabarre** [prody/ProDy#247]
Probably this is covered somewhere in the documentation but I haven't been able to find it - 

I am trying to use prody to find contacting residues given a specific reside (eg/ - what residues are within 5 A of residue 45 in the A chain?)  For instance - in pymol one would do this by:  "create selection, byresidue PDBname within 5 of (selection)"

I found the ProDy Contact Identification module & documentation.

How does one convert the output from the iterNeighbors/findNeighbors routines into actual residues.  Currently I am able to get atom indices but not able to track those back to the residue to which they belong.

Thanks in advance for the help and for creating this (mostly) open source tool.

**Comment by cihankayacihan** [comment]
Hello. Prody does not have an explicit definition of contact because in different contexts, different groups tend to use different contact definition. However, even if it is not the best, this could be useful. Thanks. 

def checkContact(res1, res2):
	coords1 = res1.getCoordsets()
	coords2 = res2.getCoordsets()

	for i in range(coords1.shape[1]):
		for j in range(coords2.shape[1]): 
			if np.linalg.norm(coords1[0,i]-coords2[0,j])<5:
				return 1
	return 0

In prody, you can use class residue instead of using atoms. Thanks.
