### ISSUE TITLE
Make ProDy available through Anaconda

### ISSUE THREAD

**Issue by cossio** [prody/ProDy#316]
I think it would be very nice if prody could be installed through

conda install prody

using Anaconda.

**Comment by cihankayacihan** [comment]
Version 1.8.2 is currently available on conda. you can download prody with `conda install prody` command. Thanks for advice.

**Comment by cossio** [comment]
@cihankayacihan I think this only works for OSX. I am on Linux.

**Comment by cihankayacihan** [comment]
I uploaded a version for linux 64 bit. But I am still having trouble for channels and I have not figure that one yet. But with the following command you can get prody through conda. `conda install -c prody_devel prody=1.8.2`

**Comment by cossio** [comment]
Now it seems to work, but I get this warning:

> The following packages will be DOWNGRADED:
> 
>     anaconda:    4.0.0-np110py27_0 --> custom-py27_0 

I'm not sure if I should proceed. Is this alright? Thanks

**Comment by cihankayacihan** [comment]
My suggestion will be using pip instead of conda. pip is also compatible with anaconda so it will be fine. I think this will not be a problem. If you have an issue you can update your anaconda and it will get back to original version. I am closing this one, if you have more inquiries please let us know.
