### ISSUE TITLE
Number of Eigenvectors different than atoms after extendModel in DNA molecule

### ISSUE THREAD

**Issue by brianjimenez** [prody/ProDy#344]
Trying to calculate ANM for a DNA molecule (attached, with txt extension because github does not support pdb extension),
[DNA_unbound.pdb.txt](https://github.com/prody/ProDy/files/646382/DNA_unbound.pdb.txt)

I don't have the same number of Eigenvectors as the number of atoms should be. PDB file contains 564 atoms, but the number of Eigenvectors after extending the initial ANM model to the whole molecule is different (it should be 564x3x3=5076 instead of 5043). Any clue?

Thank you for your help and support,
Brian

Source code:
```
molecule = parsePDB('DNA_unbound.pdb')
dna_atoms = molecule.select("name P or name C4' or name C2")
dna_anm = ANM('dna')
dna_anm.buildHessian(dna_atoms)
dna_anm.calcModes(n_modes=1)
dna_anm_ext, dna_all = extendModel(dna_anm, dna_atoms, molecule.all, norm=True)
print len(dna_all)
1681
print dna_anm_ext.numAtoms()
1681
print (dna_anm_ext.getEigvecs()).shape
(5043, 1)
```

**Comment by brianjimenez** [comment]
Please, could somebody shed some light on this?

**Comment by SHZ66** [comment]
Hi,

I think the problem is that one of the nucleotides doesn't have the C2 atom, so that the actual number of extended atoms is 1681, which is smaller than expected 564*3=1692. 

I also noticed that you only calculated one mode (`dna_anm.calcModes(**n_modes=1**)`), so 5043 should be the number of nodes in the extended model, instead of the number of eigenvectors.

**Comment by brianjimenez** [comment]
Thanks a lot for your answer, I'll check in my code that the selected atoms are always present for the selection prior to normal mode calculation. Thanks again for your help.
