### ISSUE TITLE
False bond created between last residue of one subunit to the first residue of another subunit

### ISSUE THREAD

**Issue by SamanehVasey** [prody/ProDy#364]
Hi everyone,

I am using NMWiz to perform some PCA for my protein which has multiple domains and subunits (but some parts were cut since they did not play much role in the process I am studying). However, after PCA calculation last residue of one subunit is shown as bonded to first residue of another subunit. I am using VMD plugin for all the calculations and visualizations. 

Could you please help me with this?
Thank you.

**Comment by SamVas** [comment]
In case somebody else is looking for a solution: After PCA calculation is done, you have to select protein's subunits separably (like resid 1 to 109 or resid 111 to 199, etc.) in the "coord" newly created molecule, and leaving out the last residues in each subunits, since it will connect them again.

If somebody has a better solution, I still appreciate your help.

**Comment by cihankayacihan** [comment]
We are working on this and hopefully we will have an elegant solution soon.

**Comment by jamesmkrieger** [comment]
I just use that work around too. We might have a proper solution at some point but it's not high priority.

**Comment by jamesmkrieger** [comment]
I think the problem is with the input given to VMD. If you make sure to setAtoms on the ensemble before giving it writeNMD or give an AtomGroup to writeNMD then it works fine, but I don't remember for sure.
