### ISSUE TITLE
Having issue using deformAtoms

### ISSUE THREAD

**Issue by mfmcronin96** [prody/ProDy#442]
Having an issue where I get this peculiar error when trying to run deformatoms function.

![image](https://user-images.githubusercontent.com/31975348/30951014-387f3b26-a3e6-11e7-9ca8-0192efd4966e.png)

I establish pdb = parsePDB('PDBfile'), nmd = parseNMD('NMDfile'), mode = (nmd, 0), and my desired rmsd is 1.0 (actually 1.2, but starting with 1.0)

Any help is appreciated

**Comment by mfmcronin96** [comment]
Also, I am using Prody 1.8.2 which I realize may be an issue

**Comment by jamesmkrieger** [comment]
What you want is `mode = nmd[0][0]`

parseNMD returns a tuple containing the Model and the Atomgroup. You'd use `model = nmd[0]` to get the Model. You'd then index it again to get a Mode i.e. `mode = model[0]` and indexing the tuple `nmd` directly twice is the same.

I will assume this issue is fixed and close it but you are welcome to open it if you still have a problem.
