### ISSUE TITLE
ProDy chromatin - tutorial

### ISSUE THREAD

**Issue by TerezaGerguri** [prody/ProDy#450]
Hello,

I would like to ask about any tutorial for using the functions in the chromatin package, at least a very brief "to-do-list" how to perform general analysis of HiC data would be amazing.

Thank you,
Tereza

**Comment by cihankayacihan** [comment]
It is not a part of our alpha version. We have some beta trials but we do not have a tutorial document. But we will work on it and it will be out soon.

**Comment by TerezaGerguri** [comment]
Thank you very much. Is it going to be till the end of the year?

**Comment by jamesmkrieger** [comment]
This is still on the to-do list. Sorry for the delay.

**Comment by TerezaGerguri** [comment]
Hello, 
it has been around 2 years since the original request. Would it be please possible to give just a very simple tutorial? At least file format requirements etc.

Thank you very much.

**Comment by SHZ66** [comment]
Hello, I am sorry for the delay. This is indeed long overdue, but as you may see from the pull requests, we are still making rapid changes to the chromatin module. Because the module is still under development and usages and conventions may change, we haven't made a tutorial on that. With that being said, the functions are almost ready and you can use them already in ProDy. Here is a short guide:

To load a HiC file into ProDy:
```
from prody import *

hic_file = "file_name_and_path_to_your_hic_file"
hic = parseHiC(hic_file)
```
The file can be either in [hic format](https://github.com/aidenlab/juicer/wiki/Data-Extraction) or plain text, in which case it can be either sparse format (x, y, freq) or dense format (tab separated values). `parseHiC` will give you a `HiC` instance. Then you can normalize the data by:

```
hic.normalize()
```
By default ProDy uses the VCnorm. Or you can choose [different normalization schemes](https://github.com/prody/ProDy/blob/master/prody/chromatin/norm.py) by:

```
hic.normalize(method=SQRTVCnorm)
```

In case the normalization scheme that you desired is not supported yet, you can implement your own normalization function and supply it to `hic.normalize`.

Since Hi-C data contains regions that don't have data (e.g. telomere, centromere), these regions are "masked" by the "HiC" class, you can access the mask by:
```
print(hic.mask)
```

You can turn on/off the mask by:
```
hic.masked = True
hic.masked = False
```

To perform the GNM on the `HiC`, it is a better practice to turn the mask on:
```
hic.masked = True
gnm = hic.calcGNM()
```

`gnm` will be a `MaskedGNM` instance, it behaves similar to a normal `GNM` class, and the difference is that it comes with a `gnm.mask` property just like the `HiC` class. It also has a special `gnm.fixTail` function that is implemented specifically for Hi-C in case the tail is missing. For example, if your `gnm` has only 890 loci, whereas your ATAC-seq data has 900 loci (and you know it is the tail that is missing, not the head), then you can:
```
gnm.fixTail(900)
```

There are other useful functions too, for example, [cluster](https://github.com/prody/ProDy/blob/master/prody/chromatin/cluster.py) for domain identification, etc. All the functions are in [chromatin](https://github.com/prody/ProDy/tree/master/prody/chromatin) module, and feel free to check them out. In the meantime, we will prepare a tutorial as soon as possible.

**Comment by jamesmkrieger** [comment]
This tutorial is now being added to the website so I'm closing this issue.
