### ISSUE TITLE
Can overlap value for identical protein structures be less than 0.5?

### ISSUE THREAD

**Issue by HimiTar** [prody/ProDy#778]
Hi all

Though I am not very sure if this is the right platform to ask this question as I see more questions related to troubleshooting the Prody execution errors. But here I go:

I have a set of so-called identical protein structures i.e. identical sequence with different PDB ids. I have made sure that there are no huge conformational changes between them such that the back-bone RMSD is less than 0.05 for full structure. These structures are single domain, single chain proteins. I have made sure that the equivalent residues are correct so that the comparison is between the identical residues. The squared fluctuations and cross-correlation profiles are very similar to each other for these structures. But for few cases when I calculate the mode overlap for top 10, top 20 or even 50 modes, the maximum overlap that I get is between 0.3 and 0.5. I was expecting a high overlap since there are no structural differences suggesting that the underlying network for NMA ideally should not be very different from each other. Can someone please shed some light if it is possible to get a very low overlap for two nearly identical protein structures. I can attach the PDB files I used, if required.

Separately, I also wanted to ask if the overlap values should always be bounded between 0 and 1? This is because I sometimes get a highly positive (say 0.9) and a highly negative (-0.9) overlap values from the calcOverlap() function for two identical protein structures. It would be really helpful if someone can explain why there can be a negative (-0.9) overlap value for two identical proteins?

**Comment by jamesmkrieger** [comment]
Hi,

It's absolutely fine to ask these kinds of questions here and others can then benefit from the answers too.

A negative overlap arises from correlated motions in opposite directions. This occurs because a given mode's starting direction is arbitrary. A lot of the time it is better to take the absolute value but the raw overlap can be informative too.

As for why you have low overlaps for the same protein, I think something must be wrong. Are you sure you are using the aligned structures for your analysis? If the backbone RMSD is less than 0.05 over the full structure then you should expect an absolute overlap very close to 1 for all matching modes and these will probably be in the same order and lie along the diagonal. If they are not aligned, however, then the modes will be pointing in different directions in the two cases and the overlaps would be much smaller.

Please let me know if I can clarify further.

Best wishes
James

**Comment by HimiTar** [comment]
Hi James

I sincerely thank you for such detailed answer on my queries. I realized later that though I had taken care to align the identical structures before the overlap is calculated, somehow for few cases, the structures were left unaligned. As soon as I fixed it, the problem of getting low overlap values got sorted. :-)

I would like to have one small clarification. Regarding the negative overlap values, it seems wise to take an absolute value for overlap. But you mentioned that the raw overlap value can be informative too. So do you think in the case of identical protein structures, highly negative correlation (-0.9) could mean differently? Also, for same protein from different structural context, e.g. in monomer and dimer, how informative would it be to obtain highly negative correlation values?

I hope I am able to clearly write my question here.

**Comment by jamesmkrieger** [comment]
I'm glad you sorted out the alignment problem. 

Generally, in terms of biology/physics, negative overlap doesn't really mean anything. It's just an artefact of the modes having arbitrary starting direction. When I said it can be useful, I meant that when you come to visualise the modes e.g. in VMD then it can be helpful to realise that you need to flip the modes to see them as the similar. It might be possible to draw biological meaning from a negative correlation between the modes of part of a structure if you're careful but I'd advise against it.

**Comment by HimiTar** [comment]
Hi James

I thank you for the clarification. Things are clearer now. :-)

**Comment by jamesmkrieger** [comment]
You're welcome
