### ISSUE TITLE
Prody COMD gpu issues

### ISSUE THREAD

**Issue by mrinal-shekhar** [prody/ProDy#872]
Hi 
I am trying to use COMD using Prody as VMD plugin. I think the installation was okay and the plugin opens up. However when i try to create the input files. I get the following error which i have attached.
Mrinal
![Annotation 2019-06-17 195653](https://user-images.githubusercontent.com/40069534/59644335-85c63180-913a-11e9-9f9d-0dbf52a6d43c.png)

**Comment by jamesmkrieger** [comment]
Hi Mrinal,

Thanks for reporting this error. I'll have a look into it and find a fix as soon as I can.

Are you using the latest version of CoMD from https://github.com/prody/comd?

Best wishes
James

**Comment by SnehaBheemireddy** [comment]
Even i am getting similar error. Is it mandatory to have GPU in a computer to run coMD? 
 its an error with .autopsf function.

**Comment by mrinal-shekhar** [comment]
Hi James,
Sorry for the slow response. I tried to download CoMD from the prody website. But now i am using the latest GitHub version. It now progresses beyond this point but now i get the following error: cannot read cycle no such variable. I am attaching a screenshot of the same
![Annotation 2019-06-19 125441](https://user-images.githubusercontent.com/40069534/59784906-89b89780-9291-11e9-9e29-318bad7aea28.png)

**Comment by jamesmkrieger** [comment]
@SnehaBheemireddy It's not necessary to have GPUs to run CoMD. I have code that handles the no GPU case in there too.

**Comment by jamesmkrieger** [comment]
@mrinal-shekhar Huh that's odd. It should know what cycle is. Can you send me this file that has the error on line 112 please so I can look into it in more detail. My email address is kriegerj@pitt.edu

Thanks

**Comment by jamesmkrieger** [comment]
@SnehaBheemireddy an issue with autopsf is not similar. Please can you make a separate issue with more information about that. My guess would be that you need to use an older version of VMD as I vaguely remember they changed something in autopsf but I'd need to look into it further.

**Comment by mvcdelacerna** [comment]
@jamesmkrieger I'm getting the same error, it does not know what cycle is. This is line 103 in my case, the first instance of ${cycle}:

`puts $sh_file "\$NAMD +devices  +ppn 1 min.conf > min${cycle}.log &"`

I've attached the tcl as a txt file.

[closing.txt](https://github.com/prody/ProDy/files/3341245/closing.txt)

**Comment by jamesmkrieger** [comment]
Thanks @mvcdelacerna 

That was exactly what I needed to fix this error, which we're now getting in issue #878 too. For some reason, it is trying to use the variable cycle for the initial minimisation before cycling for structure B instead of 0 like it has for structure A.

This should be fixed in https://github.com/prody/coMD/pull/59

This should also fix one of your issues @SnehaBheemireddy in issue prody/prody#878

**Comment by jamesmkrieger** [comment]
Hi @mrinal-shekhar and @mvcdelacerna,

Please let me know if everything is working now. If it is, we will update the ProDy website with the fixed version of CoMD.

Thanks again

**Comment by mvcdelacerna** [comment]
@jamesmkrieger This seems to fix the issue re cycle. I haven't run anything yet just a quick set up to see if it works. I noticed that the minimization folders are not created unless you check the run now box. Not sure if that is intentional. I'll keep playing around with this when I have more time. Thanks!

**Comment by jamesmkrieger** [comment]
Yes, this is intentional. The directories get made as part of the run procedure. If you don't check the run now box then you have to run it yourself using vmd and you can incorporate that into scripts for submitting on the cluster. If you do check run now then it should run on your current machine where you're doing the setup.

Great that the setup works. I guess this is what we were trying to fix with this issue so I can close it and you can open another one if you have any unrelated problems.
